services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ups
    ports:
      - "15432:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql

  user_product_service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "50052:50052"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: ups
    volumes:
      - .:/app # ✅ Mount the whole project for live reload
      - ~/.air:/root/.air # Optional: cache air settings
