FROM golang:1.24

# Install Air for hot reload and PostgreSQL client tools
RUN go install github.com/air-verse/air@latest && \
    apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
EXPOSE 50052

CMD ["air"]
