version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ups
    ports:
      - "15432:5432"
  ups:
    image: user_product_service:3
    ports:
      - "50051:50051"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: ups
    entrypoint: >
      sh -c "
      until pg_isready -h db -p 5432; do
        echo 'Waiting for Postgres...'; sleep 1;
      done;
      ./user_product_service"

# To run the services, use the following command:
# docker-compose up